host: {0}
acceptorPort: {1}
configVersion: 0.0.2
bundleDbVersion: 0.0.2
resourcesUrl: http://{2}/resources
configsUrl: http://{2}/config
updateConfigUrl: http://{2}/update/{{BuildTarget}}.yml
stateFileUrl: http://{2}/state/_state.yml
