host: {0}
acceptorPort: {1}
configVersion: master-48606
bundleDbVersion: master-48606
resourcesUrl: http://{2}/resources
configsUrl: http://{2}/config
updateConfigUrl: http://{2}/update/{{BuildTarget}}
stateFileUrl: http://{2}/state/_state.yml
