---
battleHints:
  collection:
    - |
      В игре два режима боевого интерфейса.
      Их можно переключить прямо в бою, нажав клавишу <color=#ffbc09>[F2]</color>.
    - |
      Танк перевернулся? Нажми Delete и взорви свой танк сам
      до того, как это сделают другие, а затем продолжи игру.
    - Игровые эффекты и управление в битве можно изменить в настройках игры.
    - |
      Нажми Enter в бою, чтобы открыть боевой чат.
      Нажми Tab для переключения между общими и командными чатами.
    - Граффити в битве можно поставить на различные поверхности
      по кнопке <color=#ffbc09>[T]</color> (англ.).
    - |
      Нажми Tab в битве, чтобы увидеть подробную статистику
      и оценить ситуацию в бою.
    - |
      Чтобы увеличить производительность игры,
      попробуйте выставить более низкий уровень качества графики.
    - Участвуй в рейтинговых боях, чтобы заработать самые ценные награды.
    - |
      Чем выше лига, тем круче сезонные награды, и тем более ценный контейнер
      ты будешь получать за участие в битвах.
    - |
      В конце рейтингового сезона очки репутации понижаются на определённый процент,
      и соревнование продолжается в новом сезоне.
    - |
      Чем выше лига — тем сложнее сражаться.
      Высокие лиги требуют хорошей прокачки модулей,
      в них сложнее заработать репутацию и проще потерять.
    - При переходе в новую лигу награда выдаётся лишь один раз за всю игру.
    - |
      Хочешь устроить настоящий голдопад? Ты можешь сам сбросить <color=#FFFF00FF>Золотой Ящик</color> в битве!
      <color=#FFFF00FF>Золотые Ящики</color> продаются в нашем игровом магазине.
    - |
      Больше битв — больше очков!
      Играй матчи до конца, чтобы получать бонусы за серию боёв, они принесут дополнительный опыт и очки в контейнер.
    - |
      Хочешь выделиться в списке игроков? 
      Поставь другую аватарку — смена и покупка доступны по клику правой клавишей на аватарке в гараже.
