---
battleHints:
  collection:
    - |
      Savaş arayüzünün iki versiyonu mevcuttur.
      Klavyede <color=#ffbc09>[F2]</color> tuşuna basarak savaş esnasında arayüz değişikliği yapabilirsin.
    - |
      Your tank has turned over? Press Delete to destroy it
      before the enemy does, then continue playing.
    - Game controls and effects can be changed in the game settings.
    - |
      Press Enter during the battle to open the chat.
      To switch between the Team and All channels, press Tab.
    - Press Tab to see statistics and ranking for the current battle.
    - |
      You can spray graffiti on different surfaces in battle,
      by pressing the <color=#ffbc09>[T]</color> key on your keyboard.
    - |
      To increase the performance of the game,
      try lowering the graphics quality.
    - Compete in Rating Battles to get most valuable rewards.
    - |
      The higher your league, the more valuable Season rewards and
      battle containers you get.
    - |
      At the end of a ranked season, the rating of every player is dropped by a certain percentage.
      The ranking race then continues in the new season.
    - |
      The higher the league, the harder the battles.
      Higher league battles require better upgrades on modules,
      it also becomes harder to earn reputation and easier to lose it.
    - |
      Want to make it rain with <color=#FFFF00FF>Gold Boxes</color> in battles? You can now drop <color=#FFFF00FF>Gold Boxes</color> yourself.
      <color=#FFFF00FF>Gold Boxes</color> are now available for sale in our in-game store.
    - |
      The more battles you play, the more points you will earn!
      If you want to earn battle streak bonus experience and container points, you will need to play every battle until its end.
    - |
      Do you want to stand out in the list of players?
      Put another avatar — changing and purchasing are available by click right mouse button on your avatar in the garage.
