errorText: |
  Для входа в игру необходимо выполнить обновление.
  Если обновление не загрузилось автоматически, перезапустите Steam.
reConnectTime: 999999 # hack: hides restart button
reportButtonLabel: ПОДРОБНЕЕ
reportUrl: https://help.tankix.com/ru/tanki-x/TODO
