---
errorText: |
  Oyunda bir güncelleme eksik.
  Eğer güncelleme otomatik olarak indirilip yüklenmediyse, lütfen Steam'i yeniden başlatın.
reConnectTime: 999999
reportButtonLabel: AYRINTILAR
reportUrl: https://help.tankix.com/en/tanki-x/TODO
