---
errorText: |
  В данный момент ведутся технические работы.
  Пожалуйста, попробуй зайти позже, или подожди, пока сервер запустится
  и игра сама восстановит соединение.
headerText: ТЕХНИЧЕСКИЕ РАБОТЫ
reportButtonLabel: НА ФОРУМ
reportUrl: http://ru.forum.tankix.com/
reConnectTime: 30
