---
errorText: Bağlantı başarısız oldu. Lütfen internet bağlantınızı kontrol edin.
reportButtonLabel: YARDIM
reportUrl: https://help.tankix.com/en/tanki-x/articles/issues/install-issues
reConnectTime: 0
