---
headerText: "СЕРВЕР ПЕРЕПОЛНЕН"
errorText: "В данный момент на сервере нет свободных мест.

Пожалуйста, подождите, пока игра подключится автоматически, как только освободится место."
reConnectTime: 30
